### ISSUE TITLE
close story 

### ISSUE THREAD

**Issue by ikishanoza** [ramon82/zuck.js#60]
I am using zuck.js in my ionic project I have tried many thing but can't find an option to close story manually. just like WhatsApp when we swipe down story got close.

any idea ? help please

**Comment by michaelolem** [comment]
Same problem here. Additionally: it does not close, it does not let the link touch, swipe has bug when I try to go back to previous story and does not work back native to Android. I am using two physical smartphones to test. One with Android 9 and one with Android 5.1 ... The problems are the same on both. Chrome 76 on both...

**Comment by salvaa000** [comment]
Esta excelente tu proyecto ramón muchísimas gracias, tengo un pequeño problema como mencionan los demás , funciona perfectamente en ordenador y dispositivos IOS pero en los android no logro poder cerrar las historias y abrir el enlace. solamente pasa la historia hasta llegar a la ultima que ya se cierra.

Como podría solucionar este problema?

Muchas gracias por todo.

**Comment by ramon82** [comment]
Fixed on last version.

**Comment by juannnesss** [comment]
Amazing work btw! but I leave another comment about this because I'm implementing this stories on my Nuxt project, and found out that I'm unable to close the stories either tapping the UI button, or the cell phone native back button.

This behavior is present just in Chrome browser and just for mobile (Android and iOS)

Tested also in the live demo, so I wonder if the demo is using the lastest version of Zuck.js

Hope this helps to fix this issue
Thanks!

**Comment by episantoshpatil** [comment]
Implemented Zuck.js latest version in ionic 4 project. Everything is working fine except android device back button. When back button is pressed, story view does not close.

help please
Thanks!
